name: Deploy to Play Store Internal
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
jobs:
  deployAabToGooglePlayInternal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v5
        with:
          distribution: 'jetbrains'
          java-version: '21'
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '4.0.3'
          bundler-cache: true

      - name: Decode Keystore
        env:
          KEYSTORE_FILE_DATA: ${{ secrets.KEYSTORE_FILE }}
          KEYSTORE_FILE_PSWD: ${{ secrets.KEYSTORE_FILE_PSWD }}
        run: |
          echo "$KEYSTORE_FILE_DATA" > keystore.asc
          gpg -d --passphrase "$KEYSTORE_FILE_PSWD" --batch keystore.asc > keystore

      - name: Decode Fastlane API Key
        env:
          API_KEY_FILE_DATA: ${{ secrets.API_KEY_FILE }}
          API_KEY_FILE_PSWD: ${{ secrets.API_KEY_FILE_PSWD }}
        run: |
          echo "$API_KEY_FILE_DATA" > fastlane-api.json.asc
          gpg -d --passphrase "$API_KEY_FILE_PSWD" --batch fastlane-api.json.asc > fastlane-api.json

      - name: Deploy to Play Store via Fastlane
        env:
          # The following env variables are used by signing configuration
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
          KEYSTORE_KEY_PSWD: ${{ secrets.KEYSTORE_KEY_PSWD }}
          KEYSTORE_PSWD: ${{ secrets.KEYSTORE_PSWD }}
        run: bundle exec fastlane deployInternal
